# Generated by Django 4.2.9 on 2024-01-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_alter_ingredient_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
